[workspace]
members = [
  "ak-core",
  "ak-contract",
  "ak-cashflow",
  "ak-repl",
  "ak-cli",
  "ak-random", "ak-sim",
]
resolver = "3"

[workspace.dependencies]
jiff = "0.2.14"
anyhow = "1.0.98"
rayon = "1.10.0"
thiserror = "1.0"
