[package]
name = "ak-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = { workspace = true }
thiserror = { workspace = true }
ak-random = { path = "../ak-random" }

[dev-dependencies]
criterion = "0.6"

[[bench]]
name = "monte_carlo_bench"
harness = false
